language: go
dist: trusty
sudo: required
install:
- go build hello.go
script:
- bash ./scripts/test.sh

deploy:
  provider: releases
    api_key:
    secure: XaCEqh+YDexSwSJ0Q2+qdXstnCoE4bvcVSjvGCyceoZXRhZd2o2mhJs8nFHe0blLFRh3ZrlKbsTooSUujf31R/qUYZW4fd8XgUMlIuiS/XkoepxL2cNxlkqSt7sbrLLbfrSuGfCxJmT4Gn8uMaFeqqT0OHZrq/NuEIo2qV3me9EE/td14wscOLBnsnVjCo2DBQV4VAHnwiMrod6k50ZLHhsjavEyHQJZ66nt14mP64xtksR7OEKnXWOO6dDhCFUVeYIhW5wPMht3KUObZuk4+VZKzeXl6tkgXfNO2LFFTFw5NiIodo4Os59lu5w9KWWjkVmQLc7oNBoTHTAb0zJ9I3gBieWckZ9unCBeJF0RqOZN5D/GsLBrmnZFo312BsXbkyh3KxDC3iyQ1F7VP483BaKtIveb2PxWSn4denoV5AHmzw10MMJ4fDVtVe0G7olprTY+UCB3uzc04Be+DEB1GV46DtWOF+4CuNK+C7/TN3V3aH8rSgIoy07Er2RW5TISqG2sdgTJoivYrmWLJwDMTv3+6YmUIsGE9eQprJJ54ikxGNiyKXrnGB1sCXfa3yDhB5KxeUnMQ3QKlC4XvpL1UPSvN6EkodTb5xWYxSBeb+Qj5F/SJrCMLVokZb7Bb7PLpU2b0t0/DBKAq1AO6qVqdUQzFgAK4MP3+WC359Uy7Cw=
  file: "hello"
  skip_cleanup: true
  on:
    repo: yaroslav-007/golang-prints-hello-binary-CI
    branch: master
    tags: true
    
